   ; DESENVOLVIDO POR EVERTON P. CRUZ
   ; COM O PROPOSITO DE USO BASE PARA OS EPISODIOS
   ; DA SERIE CONHECENDO O MICROCONTROLADOR PIC16F628A
   #INCLUDE <P16F628A.INC>
   LIST P=16F628A
   __CONFIG _BOREN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_OFF & _INTRC_OSC_NOCLKOUT
  
  ; DEFINICAO DE CONSTANTES E VARIAVEIS
  #DEFINE BOTAO	    PORTA, RA3
  #DEFINE MOTOR     PORTB, RB4
  
  ; http://golovchenko.org/cgi-bin/delay
  CBLOCK
    D1
    D2
    D3
  ENDC
    
  ORG     0x00       ; TRATAMENTO DO RESET
  GOTO    SETUP_PROCESSO

  ORG     0x04       ; TRATAMENTO DAS INTERRUPCOES
  RETFIE
    
SETUP_PROCESSO:
  ; SELECIONA O BANCO 1 DE MEMORIA
  BCF     STATUS, RP1
  BSF     STATUS, RP0

  BSF	PCON, OSCF ; CONF. FREQÜÊNCIA DO OSCILADOR INTERNO EM 4 MHz
  
  ; CONFIGURACOES DO REGISTRADOR OPTION
  MOVLW	B'10000000'
  ; 1 - NOT_RBPU    -> DESATIVA RESISTORES PULL-UP
  ; 0 - INTDEG      -> INT. ATIV. BORDA DE DESCIDA RB0
  ; 0 - TOCS        -> O CLOCK DO TIMER 0 EH INTERNO
  ; 0 - TOSE        -> BORDA DE SUBIDA NO TIMER 0, RA4
  ; 0 - PSA         -> PRESCALER ASSOCIADO AO TIMER 0
  ; 0 - PS2,PS1,PS0 -> TIMER 0 COM RAZAO 1:2
  MOVWF   OPTION_REG
    
  ; MODIFICA O COMPORTAMENTO DA PORTA
  MOVLW   B'11111111'
  ; 1 - PINO RA7 COMO ENTRADA
  ; 1 - PINO RA6 COMO ENTRADA
  ; 1 - PINO RA5 COMO ENTRADA
  ; 1 - PINO RA4 COMO ENTRADA
  ; 1 - PINO RA3 COMO ENTRADA
  ; 1 - PINO RA2 COMO ENTRADA
  ; 1 - PINO RA1 COMO ENTRADA
  ; 1 - PINO RA0 COMO ENTRADA
  MOVWF   TRISA ; CONFIGURAÇÕES DO TRISA
    
  ; MODIFICA O COMPORTAMENTO DA PORTB
  MOVLW   B'11101111'
  ; 1 - PINO RB7 COMO ENTRADA
  ; 1 - PINO RB6 COMO ENTRADA
  ; 1 - PINO RB5 COMO ENTRADA
  ; 1 - PINO RB4 COMO SAIDA
  ; 1 - PINO RB3 COMO SAIDA
  ; 1 - PINO RB2 COMO ENTRADA
  ; 1 - PINO RB1 COMO ENTRADA
  ; 1 - PINO RB0 COMO ENTRADA
  MOVWF   TRISB ; CONFIGURAÇÕES DO TRISB	    
    
  ; SELECIONA O BANCO 0 DE MEMORIA
  BCF     STATUS, RP1
  BCF     STATUS, RP0	    
    
  ; DEFINE O MODO DE OPERACAO DO COMP. ANALOG. DESLIGADOS
  MOVLW   B'00000111'
  MOVWF   CMCON	    
    
  ; CONFIGURACOES DE INTERRUPCOES
  MOVLW   B'00000000'  
  ; 0 - GIE  -> DESATIVA INT./CHAVE GERAL
  ; 0 - EEIE -> DESATIVA INT. DA EEPROM
  ; 0 - T0IE -> DESATIVA INT. NO TMR0
  ; 0 - INTE -> DESATIVA INT. NO RB0/INT
  ; 0 - RBIE -> DESATIVA INT. MUDANCA RB<7:4>
  ; 0 - T0IF -> FLAG DE TRANSBORDO DO TMR0
  ; 0 - INTF -> FLAG DE RESPOSTA INT. RB0/INT
  ; 0 - RBIF -> FLAG DE RESPOSTA INT EM RB<7:4>
  MOVWF   INTCON
    
ROTULO_A:
  BTFSS   BOTAO          ; BOTAO PRESSIONADO? SE SIM SALTA
  GOTO    ROTULO_C
  BTFSS   MOTOR          ; MOTOR LIGADO? SE SIM SALTA
  GOTO    DESLIGA_MOTOR
  GOTO    LIGA_MOTOR
ROTULO_B:
  GOTO    ESPERA_500MS
  GOTO    ROTULO_C
ROTULO_C:
  GOTO    ROTULO_A

DESLIGA_MOTOR:
  BCF     MOTOR
  GOTO    ROTULO_B

LIGA_MOTOR:
  BSF     MOTOR
  GOTO    ROTULO_B

ESPERA_500MS:
  ; Delay = 0.5 seconds
  ; Clock frequency = 4 MHz
  ; Actual delay = 0.5 seconds = 500000 cycles
  ;499994 cycles
  MOVLW   0x03
  MOVWF   D1
  MOVLW   0x18
  MOVWF   D2
  MOVLW   0x02
  MOVWF   D3
Delay_0:
  DECFSZ  D1, f
  GOTO    $+2
  DECFSZ  D2, f
  GOTO    $+2
  DECFSZ  D3, f
  GOTO    Delay_0
  ;6 cycles
  GOTO    $+1
  GOTO    $+1
  GOTO    ROTULO_C
  
  END
