 ; INSTRUCAO: MOVLW
 ; MOVE (COLOCA) O LITERAL (NUMERO) NO REGISTRADOR W
 ; OU MELHOR DIZENDO
 ; ARMAZENA O LITERAL (NUMERO) NO REGISTRADOR W
 MOVLW  B'00001011' ; ARMAZENA O LITERAL 13 (1011) NO REGISTRADOR W
 MOVLW  O'14'       ; SOBRESCREVE O VALOR 11 PELO VALOR 12 NO REG. W
 MOVLW  D'10'       ; SOBRESCREVE O VALOR 12 PELO VALOR 10 NO REG. W
 MOVLW  .10         ; SOBRESCREVE O VALOR 10 PELO VALOR 10 NO REG. W
 MOVLW  H'0B'       ; SOBRESCREVE O VALOR 10 PELO VALOR 11 NO REG. W
 MOVLW  0x0B        ; SOBRESCREVE O VALOR 11 PELO VALOR 11 NO REG. W
 MOVLW  A'%'        ; SOBRESCREVE O VALOR 12 PELO CARACTER % NO REG. W
                    ; O CARACTER EH SUBSTITUIDO PELO BYTE DA TAB. ASCII
 MOVLW  '#'         ; SOBRESCREVE CARACTER % POR CARACTER # NO REG. W
