  ; DESENVOLVIDO POR EVERTON P. CRUZ
  ; COM O PROPOSITO DE USO BASE PARA OS EPISODIOS
  ; DA SERIE CONHECENDO O MICROCONTROLADOR PIC16F628A
  #INCLUDE <P16F628A.INC>
  LIST P=16F628A
  __CONFIG _BOREN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_OFF & _INTRC_OSC_NOCLKOUT
   
  ; https://pt.wikipedia.org/wiki/SEGMENTO_De_sete_segmentos
  ; https://en.wikipedia.org/wiki/Seven-segment_display
  
  ; DEFINICAO DE CONSTANTES E VARIAVEIS
  #DEFINE BOTAO_1   PORTA, RA2 ; botao com valor 1
  #DEFINE BOTAO_2   PORTA, RA3 ; botao com valor 2
  #DEFINE BOTAO_4   PORTA, RA4 ; botao com valor 4
  #DEFINE BOTAO_8   PORTA, RA5 ; botao com valor 8
  
  #DEFINE SEGMENTO_A PORTB, RB7 ; segmento A
  #DEFINE SEGMENTO_B PORTB, RB6 ; segmento B
  #DEFINE SEGMENTO_C PORTB, RB5 ; segmento C
  #DEFINE SEGMENTO_D PORTB, RB4 ; segmento D
  #DEFINE SEGMENTO_E PORTB, RB3 ; segmento E
  #DEFINE SEGMENTO_F PORTB, RB2 ; segmento F
  #DEFINE SEGMENTO_G PORTB, RB1 ; segmento G
  #DEFINE SEGMENTO_P PORTB, RB0 ; ponto
  
  #DEFINE CONTADOR  0x20       ; registrador para armazenar adições
  
  ORG     0x00       ; TRATAMENTO DO RESET
  GOTO    SETUP_PROCESSO

  ORG     0x04       ; TRATAMENTO DAS INTERRUPCOES
  RETFIE
    
SETUP_PROCESSO:
  ; SELECIONA O BANCO 1 DE MEMORIA
  BCF   STATUS, RP1
  BSF   STATUS, RP0

  BSF	PCON, OSCF ; CONF. FREQÜÊNCIA DO OSCILADOR INTERNO EM 4 MHz
  
  ; CONFIGURACOES DO REGISTRADOR OPTION
  MOVLW	B'10000000'
  ; 1 - NOT_RBPU    -> DESATIVA RESISTORES PULL-UP
  ; 0 - INTDEG      -> INT. ATIV. BORDA DE DESCIDA RB0
  ; 0 - TOCS        -> O CLOCK DO TIMER 0 EH INTERNO
  ; 0 - TOSE        -> BORDA DE SUBIDA NO TIMER 0, RA4
  ; 0 - PSA         -> PRESCALER ASSOCIADO AO TIMER 0
  ; 0 - PS2,PS1,PS0 -> TIMER 0 COM RAZAO 1:2
  MOVWF OPTION_REG
    
  ; MODIFICA O COMPORTAMENTO DA PORTA
  MOVLW B'11111111'
  ; 1 - PINO RA7 COMO ENTRADA
  ; 1 - PINO RA6 COMO ENTRADA
  ; 1 - PINO RA5 COMO ENTRADA
  ; 1 - PINO RA4 COMO ENTRADA
  ; 1 - PINO RA3 COMO ENTRADA
  ; 1 - PINO RA2 COMO ENTRADA
  ; 1 - PINO RA1 COMO ENTRADA
  ; 1 - PINO RA0 COMO ENTRADA
  MOVWF TRISA ; CONFIGURAÇÕES DO TRISA
    
  ; MODIFICA O COMPORTAMENTO DA PORTB
  ;MOVLW   B'00000000'
  ; 1 - PINO RB7 COMO SAIDA
  ; 1 - PINO RB6 COMO SAIDA
  ; 1 - PINO RB5 COMO SAIDA
  ; 1 - PINO RB4 COMO SAIDA
  ; 1 - PINO RB3 COMO SAIDA
  ; 1 - PINO RB2 COMO SAIDA
  ; 1 - PINO RB1 COMO SAIDA
  ; 1 - PINO RB0 COMO SAIDA
  ;MOVWF   TRISB ; CONFIGURAÇÕES DO TRISB
  CLRF  TRISB
    
  ; SELECIONA O BANCO 0 DE MEMORIA
  BCF   STATUS, RP1
  BCF   STATUS, RP0	    
    
  ; DEFINE O MODO DE OPERACAO DO COMP. ANALOG. DESLIGADOS
  MOVLW B'00000111'
  MOVWF CMCON	    
    
  ; CONFIGURACOES DE INTERRUPCOES
  ;MOVLW   B'00000000'  
  ; 0 - GIE  -> DESATIVA INT./CHAVE GERAL
  ; 0 - EEIE -> DESATIVA INT. DA EEPROM
  ; 0 - T0IE -> DESATIVA INT. NO TMR0
  ; 0 - INTE -> DESATIVA INT. NO RB0/INT
  ; 0 - RBIE -> DESATIVA INT. MUDANCA RB<7:4>
  ; 0 - T0IF -> FLAG DE TRANSBORDO DO TMR0
  ; 0 - INTF -> FLAG DE RESPOSTA INT. RB0/INT
  ; 0 - RBIF -> FLAG DE RESPOSTA INT EM RB<7:4>
  ;MOVWF INTCON
  CLRF  INTCON
  
PRINCIPAL:
  CLRW

SOMA_1:
  BTFSS BOTAO_1
  GOTO  SOMA_2
  ADDLW .1
  
SOMA_2:
  BTFSS BOTAO_2
  GOTO  SOMA_4
  ADDLW .2
    
SOMA_4:
  BTFSS BOTAO_4
  GOTO  SOMA_8
  ADDLW .4

SOMA_8:
  BTFSS BOTAO_8
  GOTO  EXIBE_VALOR
  ADDLW .8
    
EXIBE_VALOR:
  MOVWF CONTADOR

TESTA_0:
  XORLW 0x00
  BTFSS STATUS, Z
  GOTO  TESTA_1
MOSTRA_0:
  ; 0 - segmentos a, b, c, d, e, f
  BSF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BCF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_1:
  MOVF  CONTADOR, 0
  XORLW 0x01
  BTFSS STATUS, Z
  GOTO  TESTA_2
MOSTRA_1:
  ; 1 - b, c
  BCF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BCF  SEGMENTO_D
  BCF  SEGMENTO_E
  BCF  SEGMENTO_F
  BCF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_2:
  MOVF  CONTADOR, 0
  XORLW 0x02
  BTFSS STATUS, Z
  GOTO  TESTA_3
MOSTRA_2:
  ; 2 - a, b, d, e, g
  BSF  SEGMENTO_A
  BSF  SEGMENTO_B
  BCF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BCF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_3:
  MOVF  CONTADOR, 0
  XORLW 0x03
  BTFSS STATUS, Z
  GOTO  TESTA_4
MOSTRA_3:
  ; 3  - a, b, c, d, g
  BSF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BSF  SEGMENTO_D
  BCF  SEGMENTO_E
  BCF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_4:
  MOVF  CONTADOR, 0
  XORLW 0x04
  BTFSS STATUS, Z
  GOTO  TESTA_5
MOSTRA_4:
  ; 4 - b, c, f, g
  BCF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BCF  SEGMENTO_D
  BCF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_5:
  MOVF  CONTADOR, 0
  XORLW 0x05
  BTFSS STATUS, Z
  GOTO  TESTA_6
MOSTRA_5:
  ; 5 - a, c, d, f, g
  BSF  SEGMENTO_A
  BCF  SEGMENTO_B
  BSF  SEGMENTO_C
  BSF  SEGMENTO_D
  BCF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_6:
  MOVF  CONTADOR, 0
  XORLW 0x06
  BTFSS STATUS, Z
  GOTO  TESTA_7
MOSTRA_6:
  ; 6 - a, c, d, e, f, g
  BSF  SEGMENTO_A
  BCF  SEGMENTO_B
  BSF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_7:
  MOVF  CONTADOR, 0
  XORLW 0x07
  BTFSS STATUS, Z
  GOTO  TESTA_8
MOSTRA_7:
  ; 7 - a, b, c
  BSF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BCF  SEGMENTO_D
  BCF  SEGMENTO_E
  BCF  SEGMENTO_F
  BCF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_8:
  MOVF  CONTADOR, 0
  XORLW 0x08
  BTFSS STATUS, Z
  GOTO  TESTA_9
MOSTRA_8:
  ; 8 - a, b, c, d, e, f, g
  BSF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_9:
  MOVF  CONTADOR, 0
  XORLW 0x09
  BTFSS STATUS, Z
  GOTO  TESTA_A
MOSTRA_9:
  ; 9 - a, b, c, f, g
  BSF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BCF  SEGMENTO_D
  BCF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_A:
  MOVF  CONTADOR, 0
  XORLW 0x0A
  BTFSS STATUS, Z
  GOTO  TESTA_B
MOSTRA_A:
  ; A (maiúsculo) - a, b, c, e, f, g
  BSF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BCF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_B:
  MOVF  CONTADOR, 0
  XORLW 0x0B
  BTFSS STATUS, Z
  GOTO  TESTA_C
MOSTRA_B:
  ;B (minúsculo) - c, d, e, f, g
  BCF  SEGMENTO_A
  BCF  SEGMENTO_B
  BSF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_C:
  MOVF  CONTADOR, 0
  XORLW 0x0C
  BTFSS STATUS, Z
  GOTO  TESTA_D
MOSTRA_C:
  ; C (maiúsculo) - a, d, e, f
  BSF  SEGMENTO_A
  BCF  SEGMENTO_B
  BCF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BCF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_D:
  MOVF  CONTADOR, 0
  XORLW 0x0D
  BTFSS STATUS, Z
  GOTO  TESTA_E
MOSTRA_D:
  ; D (minúsculo) - b, c, d, e, g
  BCF  SEGMENTO_A
  BSF  SEGMENTO_B
  BSF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BCF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_E:
  MOVF  CONTADOR, 0
  XORLW 0x0E
  BTFSS STATUS, Z
  GOTO  TESTA_F
MOSTRA_E:
  ; E (maiúsculo) - a, d, e, f, g
  BSF  SEGMENTO_A
  BCF  SEGMENTO_B
  BCF  SEGMENTO_C
  BSF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL

TESTA_F:
  MOVF  CONTADOR, 0
  XORLW 0x0F
  BTFSS STATUS, Z
  GOTO  PRINCIPAL
MOSTRA_F:
  ; F (maiúsculo) - a, e, f, g
  BSF  SEGMENTO_A
  BCF  SEGMENTO_B
  BCF  SEGMENTO_C
  BCF  SEGMENTO_D
  BSF  SEGMENTO_E
  BSF  SEGMENTO_F
  BSF  SEGMENTO_G
  GOTO PRINCIPAL
  
  END
