  ; DESENVOLVIDO POR EVERTON P. CRUZ
  ; COM O PROPOSITO DE USO BASE PARA OS EPISODIOS
  ; DA SERIE CONHECENDO O MICROCONTROLADOR PIC16F628A
  #INCLUDE <P16F628A.INC>
  LIST P=16F628A
  __CONFIG _BODEN_ON & _MCLRE_ON & _LVP_OFF & _WDT_OFF & INTOSC & _CP_OFF & _PWRTE_ON
  
  #DEFINE W_TEMP        0x20
  #DEFINE STATUS_TEMP   0x21
  #DEFINE COUNTER       0x22
  #DEFINE PASS_LIM_LOW  0x23
  #DEFINE PASS_LIM_HIGH 0x26
  #DEFINE VAR_TIME      0x27
  #DEFINE ROW_1         PORTB, RB0
  #DEFINE ROW_2         PORTB, RB1
  #DEFINE ROW_3         PORTB, RB2
  #DEFINE ROW_4         PORTB, RB3
  ;#DEFINE COLUMN_1     PORTB, RB4
  ;#DEFINE COLUMN_2     PORTB, RB5
  ;#DEFINE COLUMN_3     PORTB, RB6
  ;#DEFINE COLUMN_4     PORTB, RB7
  #DEFINE DOOR          PORTA, RA0
  #DEFINE LED_STOP      PORTA, RA1
  #DEFINE LED_GO        PORTA, RA2
  #DEFINE PASS_VALUE_1  0x11 ; VALUE 1
  #DEFINE PASS_VALUE_2  0x22 ; VALUE 5
  #DEFINE PASS_VALUE_3  0x44 ; VALUE 9
  #DEFINE PASS_VALUE_4  0x88 ; VALUE D

  ORG     0x00
  GOTO    INICIAPARAMETROS

  ORG     0x04
  MOVWF   W_TEMP
  SWAPF   STATUS, 0
  MOVWF   STATUS_TEMP

  BTFSS   INTCON, RBIF
  GOTO    SAIDA_INTERRUPCAO

  INCF    COUNTER

KEY_1:
  MOVLW   0x11 ; KEY 1
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_2
  GOTO    STEP_COUNTER
  
KEY_2:
  MOVLW   0x21 ; KEY 2
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_3
  GOTO    STEP_COUNTER
  
KEY_3:
  MOVLW   0x41 ; KEY 3
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_A
  GOTO    STEP_COUNTER

KEY_A:
  MOVLW   0x81 ; KEY A
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_4
  GOTO    STEP_COUNTER

KEY_4:
  MOVLW   0x12 ; KEY 4
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_5
  GOTO    STEP_COUNTER

KEY_5:
  MOVLW   0x22 ; KEY 5
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_6
  GOTO    STEP_COUNTER

KEY_6:
  MOVLW   0x42 ; KEY 6
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_B
  GOTO    STEP_COUNTER

KEY_B:
  MOVLW   0x82 ; KEY B
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_7
  GOTO    STEP_COUNTER

KEY_7:
  MOVLW   0x14 ; KEY 7
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_8
  GOTO    STEP_COUNTER

KEY_8:
  MOVLW   0x24 ; KEY 8
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_9
  GOTO    STEP_COUNTER

KEY_9:
  MOVLW   0x44 ; KEY 9
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_C
  GOTO    STEP_COUNTER

KEY_C:
  MOVLW   0x84 ; KEY C
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_ASTERISC
  GOTO    STEP_COUNTER

KEY_ASTERISC:
  MOVLW   0x18 ; KEY *
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_0
  GOTO    STEP_COUNTER

KEY_0:
  MOVLW   0x28 ; KEY 0
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_HASH
  GOTO    STEP_COUNTER

KEY_HASH:
  MOVLW   0x48 ; KEY #
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    KEY_D
  GOTO    STEP_COUNTER

KEY_D:
  MOVLW   0x88 ; KEY D
  XORWF   PORTB, 0
  BTFSS   STATUS, Z
  GOTO    CLEAR_FLAG_STATE_CHANGE
  ;GOTO    STEP_COUNTER

STEP_COUNTER:
  MOVF    PORTB, 0
  MOVWF   COUNTER
  MOVLW   PASS_M_4
  XORLW   COUNTER
  BTFSS   STATUS, Z
  GOTO    CLEAR_FLAG_STATE_CHANGE

  ; VERIFY PASSWORD
  MOVLW   PASS_V_1
  XORWF   PASS_M_1, 0
  BTFSS   STATUS, Z
  GOTO    NO_ACCESS

  MOVLW   PASS_V_2
  XORWF   PASS_M_2, 0
  BTFSS   STATUS, Z
  GOTO    NO_ACCESS

  MOVLW   PASS_V_3
  XORWF   PASS_M_3, 0
  BTFSS   STATUS, Z
  GOTO    NO_ACCESS

  MOVLW   PASS_V_4
  XORWF   PASS_M_4, 0
  BTFSS   STATUS, Z
  GOTO    NO_ACCESS
  ;GOTO    YES_ACCESS

YES_ACCESS:
  BSF     LED_GO
  BSF     DOOR
  CALL    WAIT_1_SECONDS
  BCF     LED_GO
  BCF     DOOR
  GOTO    RESET_COUNTER  

NO_ACCESS:
  BSF     LED_STOP
  BCF     DOOR
  CALL    WAIT_1_SECONDS
  BCF     LED_STOP
  ;GOTO    RESET_COUNTER

RESET_COUNTER:
  MOVLW   PASS_M_1
  MOVWF   COUNTER

CLEAR_FLAG_STATE_CHANGE:
  BCF     INTCON, RBIF

SAIDA_INTERRUPCAO:
  SWAPF   STATUS_TEMP, 0
  MOVWF   STATUS
  MOVF    W_TEMP, 0
  RETFIE

WAIT_1_SECONDS:
  NOP
  RETURN

INICIAPARAMETROS:
  BCF     STATUS, RP1
  BSF     STATUS, RP0

  MOVLW   B'10000000'
  MOVWF   OPTION_REG

  CLRF    PIE1

  MOVLW   B'11111000'
  MOVWF   TRISA

  MOVLW   B'11110000'
  MOVWF   TRISB

  BCF     STATUS, RP1
  BCF     STATUS, RP0

  MOVLW   B'00000111'
  MOVWF   CMCON

  MOVLW   PASS_M_1
  MOVWF   COUNTER

  MOVLW   B'10001000'
  MOVWF   INTCON

PROGRAMAPRINCIPAL:
  BSF     ROW_1
  CALL    ESPERA_1_MS
  BCF     ROW_1

  BSF     ROW_2
  CALL    ESPERA_1_MS
  BCF     ROW_2

  BSF     ROW_3
  CALL    ESPERA_1_MS
  BCF     ROW_3

  BSF     ROW_4
  CALL    ESPERA_1_MS
  BCF     ROW_4

  GOTO    PROGRAMAPRINCIPAL

ESPERA_1_MS:
  MOVLW   .250
  MOVWF   VAR_TIME
loop1:
  NOP
  DECFSZ  0x20
  GOTO    loop1
  RETURN
  
  END