  ; DESENVOLVIDO POR EVERTON P. CRUZ
  ; COM O PROPOSITO DE USO NO EPISODIO 12
  ; DA SERIE CONHECENDO O MICROCONTROLADOR PIC16F628A
  #INCLUDE <P16F628A.INC>
  LIST P=16F628A
  __CONFIG _BOREN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_OFF & _INTRC_OSC_NOCLKOUT

  ; DEFINICAO DE VARIAVEIS
  #DEFINE W_TEMP      0x20
  #DEFINE STATUS_TEMP 0x21
  #DEFINE BOTAO       PORTB, RB0
  #DEFINE LED_GREEN   PORTA, RA0
  #DEFINE LED_RED     PORTA, RA1

  ORG     0x00       ; TRATAMENTO DO RESET
  GOTO    INICIAPARAMETROS

  ORG     0x04       ; TRATAMENTO DAS INTERRUPCOES
  MOVWF   W_TEMP
  SWAPF   STATUS, 0
  MOVWF   STATUS_TEMP

  BTFSS   INTCON, INTF
  GOTO    SAIDA_INTERRUPCAO
  BCF     INTCON, INTF
  BCF     LED_GREEN
  BSF     LED_RED
  BTFSS   BOTAO
  GOTO    $-1
  BCF     LED_RED

SAIDA_INTERRUPCAO:
  SWAPF   STATUS_TEMP, 0
  MOVWF   STATUS
  MOVF    W_TEMP, 0
  RETFIE 

INICIAPARAMETROS:
  BCF     STATUS, RP1
  BSF     STATUS, RP0

  MOVLW   B'11000000'
  MOVWF   OPTION_REG

  CLRF    PIE1

  MOVLW   B'11111100'
  MOVWF   TRISA

  MOVLW   B'11111111'
  MOVWF   TRISB

  BCF     STATUS, RP1
  BCF     STATUS, RP0

  MOVLW   B'00000111'
  MOVWF   CMCON

  MOVLW   B'10010000'
  MOVWF   INTCON

PROGRAMAPRINCIPAL:
  BTFSS   LED_GREEN
  BSF     LED_GREEN
  GOTO    PROGRAMAPRINCIPAL

  END